#!/usr/bin/env bash
# This script pings an IP address passed as an argument 5 times.

# Display usage if no argument provided and exit
[[ -z "$1" ]] && echo "Usage: $0 {IP_ADDRESS}" && exit 1

# Ping the provided IP address 5 times
ping -c 5 "$1"
